name: Destroy Infrastructure

on:
  workflow_dispatch: # Manual trigger

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Init Terraform - Bootstrap
        working-directory: infra-1/bootstrap
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=my-react-node-app-bucket02" \
            -backend-config="key=bootstrap.tfstate" \
            -backend-config="region=us-east-1"

      - name: Destroy Terraform - Bootstrap
        working-directory: infra-1/bootstrap
        run: terraform destroy -auto-approve

      - name: Init Terraform - Main
        working-directory: infra-1/main
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=my-react-node-app-bucket02" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: Destroy Terraform - Main
        working-directory: infra-1/main
        run: terraform destroy -auto-approve

