name: Frontend Deploy (S3/CloudFront)

on:
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    needs: [infra, backend]  # Ensure infra and backend are ready
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init & Apply (Frontend)
        working-directory: infra-1/main
        run: |
          terraform init -reconfigure
          terraform plan -var-file=dev.tfvars
          terraform apply -auto-approve -var-file=dev.tfvars

