name: Terraform Infrastructure

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  # -----------------------------
  # Job 1: Deploy Main Infrastructure
  # -----------------------------
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra-1/main
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      # 4️⃣ Cache Terraform providers
      - name: Cache Terraform Providers
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            infra-1/main/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      # 5️⃣ Wait for S3 bucket propagation (if needed)
      - name: Wait for S3 bucket
        run: |
          BUCKET_NAME="my-react-node-app-bucket02"
          for i in {1..6}; do
            if aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
              echo "S3 bucket exists and is ready"
              break
            else
              echo "Waiting for S3 bucket to be ready..."
              sleep 10
            fi
          done

      # 6️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init -reconfigure

      # 7️⃣ Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 8️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars

      # 9️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=dev.tfvars

  # -----------------------------
  # Job 2: Destroy Infrastructure
  # -----------------------------
  destroy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra-1/main
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      # 3️⃣ Cache Terraform providers
      - name: Cache Terraform Providers
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init -reconfigure -backend-config="bucket=my-react-node-app-bucket02" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"

      # 5️⃣ Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=dev.tfvars

  destroy-bootstrap:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra-1/bootstrap
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      # 3️⃣ Cache Terraform providers
      - name: Cache Terraform Providers
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init -reconfigure

      # 5️⃣ Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve

